# Example provider.yaml with Let's Encrypt configuration
# This file shows how to configure the Akash provider with automatic SSL/TLS certificate management
#
# Usage: helm install akash-provider akash/provider -f provider.yaml
#
# Note: If no storage class is specified in attributes, the chart will use 'local-path' 
# storage class by default. Ensure the Rancher Local Path Provisioner is installed:
# kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.32/deploy/local-path-storage.yaml

# Standard provider configuration
from: akash1<your-provider-address>
key: LS0tLS1CRU<your-key>
keysecret: QUtB<your-key-secret>
domain: your-provider-domain.com
node: http://<rpc-address>:26657
withdrawalperiod: 12h

# Let's Encrypt configuration (HTTP challenge is default)
letsEncrypt:
  enabled: true
  # Email will be auto-detected from the 'email' field above
  # HTTP challenge port (default: 5002)
  acme:
    httpChallengePort: 5002
  # Optional: DNS providers for DNS challenge
  providers:
    cloudflare:
      enabled: false
      apiToken: "your-cloudflare-api-token"
    googleCloud:
      enabled: false
      serviceAccount:
        content: "your-google-cloud-service-account-json"

>>>>>>> main-to-devel
# Provider attributes
attributes:
  - key: region
    value: us-west
  - key: host
    value: akash
  - key: tier
    value: community
  - key: organization
    value: mycompany
  # Storage capabilities - Let's Encrypt PVC will use beta2 storage class
  # If not specified, will default to 'local-path' storage class
  - key: capabilities/storage/1/class
    value: beta2
  - key: capabilities/storage/1/persistent
    value: true
