apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-ip
  namespace: akash-services
data:
  provider-address: {{ .Values.provider_address | default "" | quote }}
  k8s-manifest-ns: "lease"
  prune-interval: "600s"
  ignore-list-entry-limit: "131072"
  web-refresh-interval: "5s"
  retry-delay: "3s"
  ignore-list-age-limit: "2613600s"
  event-failure-limit: "3"
