apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-bidscripts
  namespace: {{ .Release.Namespace }}
data:
  price_script_chia.sh: |
{{ tpl (.Files.Get "scripts/price_script_chia.sh") . | indent 4 }}
