apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
data:
  dummy: |
    dummy
{{- if .Values.bidpricescript }}
  price_script.sh: |
{{ .Values.bidpricescript | b64dec | indent 4 }}
{{- end }}
  liveness_checks.sh: |
{{ tpl (.Files.Get "scripts/liveness_checks.sh") . | indent 4 }}
