{{- if .Values.bidpricescriptname -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-bidscripts
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.bidpricescriptname }}: |
{{ tpl (.Files.Get (printf "scripts/%s" .Values.bidpricescriptname)) . | indent 4 }}
{{- end }}
