apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: akash-provider-deployment-restart
  namespace: akash-services
spec:
  concurrencyPolicy: Forbid
  schedule: '0 8 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: akash-provider
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/akash-provider'
                - '-n akash-services'
