{{- if .Values.letsEncrypt.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "provider.fullname" . }}-letsencrypt-challenge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
  annotations:
    # Let's Encrypt HTTP challenge ingress
    # Remove nginx-specific annotations for akash-ingress-class
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - host: provider.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "provider.fullname" . }}
            port:
              number: 80
{{- end }}