{{- if .Values.letsEncrypt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-letsencrypt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
data:
  # Let's Encrypt configuration extracted from provider.yaml
  # Environment variables use AP_ prefix (cosmos-sdk convention)
  AP_CERT_ISSUER_ENABLED: "true"
  {{- if .Values.letsEncrypt.acme.email }}
  AP_CERT_ISSUER_EMAIL: {{ .Values.letsEncrypt.acme.email | quote }}
  {{- end }}
  {{- if .Values.letsEncrypt.acme.caDirUrl }}
  AP_CERT_ISSUER_CA_DIR_URL: {{ .Values.letsEncrypt.acme.caDirUrl | quote }}
  {{- end }}
  {{- if and .Values.letsEncrypt.acme.externalAccountBinding .Values.letsEncrypt.acme.externalAccountBinding.kid }}
  AP_CERT_ISSUER_KID: {{ .Values.letsEncrypt.acme.externalAccountBinding.kid | quote }}
  {{- end }}
  {{- if and .Values.letsEncrypt.acme.externalAccountBinding .Values.letsEncrypt.acme.externalAccountBinding.hmac }}
  AP_CERT_ISSUER_HMAC: {{ .Values.letsEncrypt.acme.externalAccountBinding.hmac | quote }}
  {{- end }}
  {{- if .Values.letsEncrypt.dns.providers }}
  AP_CERT_ISSUER_DNS_PROVIDERS: {{ join "," .Values.letsEncrypt.dns.providers | quote }}
  {{- end }}
{{- end }}
