{{- if .Values.letsEncrypt.enabled }}
{{- if .Values.letsEncrypt.providers.cloudflare.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider.fullname" . }}-cloudflare-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
type: Opaque
data:
  CF_DNS_API_TOKEN: {{ .Values.letsEncrypt.providers.cloudflare.apiToken | b64enc }}
{{- end }}

{{- if .Values.letsEncrypt.providers.googleCloud.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider.fullname" . }}-gcp-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: {{ .Files.Get .Values.letsEncrypt.providers.googleCloud.serviceAccount.file | b64enc }}
{{- end }}
{{- end }}
