apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    akash.network: "true"
    app.kubernetes.io/component: operator
    {{- include "provider.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: api
    protocol: TCP
    port: 8443
    targetPort: api
  - name: grpc
    protocol: TCP
    port: 8444
    targetPort: grpc
  selector:
    app: {{ include "provider.fullname" . }}
    {{- include "provider.selectorLabels" . | nindent 4 }}
