apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console-api.fullname" . }}
  namespace: {{ .Values.namespace | default "staging" }}
  labels:
    {{- include "console-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "console-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "console-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "console-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/server.js"]
          ports:
            - containerPort: 3000
              name: api-port
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "console-api.dopplerSecretName" . }}
