apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
    spec:
      containers:
        - name: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 3000
              name: api-port
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
          {{- if and .Values.doppler (and .Values.doppler.project .Values.doppler.config) }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}-secret
          {{- end }}