apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.chain }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-{{ .Values.chain }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.chain }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-{{ .Values.chain }}
    spec:
      containers:
        - name: {{ .Values.appName }}-{{ .Values.chain }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["node", "dist/server.js"]
          ports:
            - containerPort: 3000
              name: api-port
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}-{{ .Values.chain }}-secret
