{{- if and .Values.doppler.project .Values.doppler.config }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.appName }}-{{ .Values.chain }}-dopplersecret
  namespace: doppler-operator-system
spec:
  config: {{ .Values.dopplerConfig }}
  managedSecret:
    name: {{ .Values.appName }}-{{ .Values.chain }}-secret
    namespace: {{ .Values.namespace }}
    type: Opaque
  project: {{ .Values.doppler.project }}
  tokenSecret:
    name: console-token-secret
  verifyTLS: true
{{- end }}