apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.appName }}-{{ .Values.chain }}-dopplersecret
  namespace: doppler-operator-system
spec:
  config: staging-mainnet
  managedSecret:
    name: {{ .Values.appName }}-{{ .Values.chain }}-secret
    namespace: {{ .Values.namespace }}
    type: Opaque
  project: {{ .Values.appName }}
  tokenSecret:
    name: console-token-secret
  verifyTLS: true
