apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: console-api-{{ .Values.global.environment }}-dopplersecret
  namespace: doppler-operator-system
spec:
  config: {{ index .Values.environments .Values.global.environment "doppler" "config" }}
  managedSecret:
    name: console-api-{{ .Values.global.environment }}-secret
    namespace: {{ .Values.global.namespace }}
    type: Opaque
  project: console-api
  tokenSecret:
    name: console-token-secret
  verifyTLS: true
