apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "console-api.fullname" . }}-dopplersecret
  namespace: {{ .Values.doppler.namespace | default "doppler-operator-system" }}
  labels:
    {{- include "console-api.labels" . | nindent 4 }}
spec:
  project: {{ .Values.doppler.project | default "console-api" }}
  config: {{ include "console-api.dopplerConfig" . }}
  managedSecret:
    name: {{ include "console-api.dopplerSecretName" . }}
    namespace: {{ .Values.namespace | default "staging" }}
    type: Opaque
  tokenSecret:
    name: {{ .Values.doppler.tokenSecret | default "console-token-secret" }}
  verifyTLS: {{ .Values.doppler.verifyTLS | default true }}
