apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-api-{{ .Values.global.environment }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ index .Values.environments .Values.global.environment "host" }}
      http:
        paths:
          - backend:
              service:
                name: console-api-{{ .Values.global.environment }}-service
                port:
                  name: {{ .Values.service.targetPort }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ index .Values.environments .Values.global.environment "host" }}
      secretName: console-api-staging-akash-network-tls

---
