{{- range .Values.jobs }}
{{- $job := mergeOverwrite (deepCopy $.Values.jobDefaults) . }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Chart.Name }}-{{ $.Values.chain }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
      successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
      template:
        metadata:
          labels:
            job: {{ $.Chart.Name }}-{{ $.Values.chain }}-{{ .name }}
        spec:
          restartPolicy: {{ $job.restartPolicy }}
          containers:
            - name: {{ $.Chart.Name }}-{{ $.Values.chain }}
              image: ghcr.io/akash-network/console-api:{{ $.Values.appVersion }}
              imagePullPolicy: "Always"
              command: {{ .command | toJson }}
              resources:
                {{- toYaml $job.resources | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ $.Chart.Name }}-{{ $.Values.chain }}-secret
                - configMapRef:
                    name: {{ $.Chart.Name }}-{{ $.Values.chain }}-config
              env:
                - name: POSTGRES_BACKGROUND_JOBS_SCHEMA
                  value: pgboss_{{ $.Values.chain }}
                - name: NETWORK
                  value: {{ $.Values.chain }}
{{- end }}
