apiVersion: v1
kind: Service
metadata:
  name: {{ include "console-api.fullname" . }}-service
  namespace: {{ .Values.namespace | default "staging" }}
  labels:
    {{- include "console-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "console-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 3000 }}
      targetPort: api-port
      name: api-port
