apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}{{ if .Values.chain }}-{{ .Values.chain }}{{ end }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: api-port
      name: api-port
  type: ClusterIP
