apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.chain }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}-{{ .Values.chain }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: api-port
      name: api-port
  type: ClusterIP
