apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akash-hostname-operator.fullname" . }}
  labels:
    {{- include "akash-hostname-operator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "akash-hostname-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "akash-hostname-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "akash-hostname-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
{{- if eq .Values.beta false }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- end }}
{{- if eq .Values.beta true }}
          image: "{{ .Values.image.provider_services_repository }}:{{ .Values.image.provider_services_tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/boot/run.sh"]
          ports:
            - name: status
              containerPort: 8085
          env:
{{- if eq .Values.beta false }}
            - name: AKASH_K8S_MANIFEST_NS
              value: lease
{{- end }}
{{- if eq .Values.beta true }}
            - name: AP_K8S_MANIFEST_NS
              value: lease
{{- end }}
          volumeMounts:
            - name: boot
              mountPath: /boot
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: boot
          configMap:
            name: akash-{{ include "akash-hostname-operator.fullname" . }}-boot
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
