apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
  annotations:
    secrets.doppler.com/reload: 'true'
spec:
  replicas: {{ .Values.providersSync.replicas | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
          image: ghcr.io/akash-network/console-provider-inventory:{{ .Values.appVersion }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              name: api-port
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-{{ .Values.chain }}-secret
            - configMapRef:
                name: {{ .Chart.Name }}-{{ .Values.chain }}-config
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ .Chart.Name }}-{{ .Values.chain }}-providers-sync
            - name: INTERFACE
              value: "providers-sync"
          resources:
            {{- toYaml .Values.providersSync.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /private/v1/healthz/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /private/v1/healthz/liveness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
