apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-{{ .Values.chain }}-migrations-dopplersecret
  namespace: doppler-operator-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  config: {{ .Values.migrations.dopplerConfig | default (printf "%s_migrations" .Release.Namespace) }}
  managedSecret:
    name: {{ .Chart.Name }}-{{ .Values.chain }}-migrations-secret
    namespace: {{ .Release.Namespace }}
    type: Opaque
  project: {{ .Chart.Name }}
  tokenSecret:
    name: console-token-secret
  verifyTLS: true
