apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: provider-console-api-dopplersecret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: console-token-secret
  project: provider-console-api
  config: staging
  managedSecret:
    name: provider-console-api-secret
    namespace: staging
