apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akash-e2e.fullname" . }}-keys
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  key-pass.txt: {{ .Values.keysecret | quote }}
  primary-key.pem: {{ .Values.primary_key | quote }}
  check-0-key.pem: {{ .Values.check_key_0 | quote }}
  check-1-key.pem: {{ .Values.check_key_1 | quote }}
  check-2-key.pem: {{ .Values.check_key_2 | quote }}
  check-3-key.pem: {{ .Values.check_key_3 | quote }}
  check-0-cert.pem: {{ .Values.check_cert_0 | quote }}
  check-1-cert.pem: {{ .Values.check_cert_1 | quote }}
  check-2-cert.pem: {{ .Values.check_cert_2 | quote }}
  check-3-cert.pem: {{ .Values.check_cert_3 | quote }}
