apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: ghcr.io/akash-network/provider-console:{{ .Values.appVersion }}{{ if eq .Release.Namespace "staging" }}-beta{{ end }}
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
