apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.appName }}-{{ .Values.namespace }}-dopplersecret
  namespace: {{ .Values.namespace }}
spec:
  tokenSecret:
    name: console-token-secret
  project: {{ .Values.dopplerProject }}
  config: {{ .Values.dopplerConfig }}
  managedSecret:
    name: {{ .Values.appName }}-secret
    namespace: {{ .Values.namespace }}
