apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: staging
  name: provider-console-security-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "140"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "140"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "140"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - provider-console-security.akash.network
      secretName: provider-console-security-akash-network-tls
  rules:
    - host: provider-console-security.akash.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: provider-console-security-service
                port:
                  number: 3000
