apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-rest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: api-port
      name: api-port
  type: ClusterIP
