apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.chain }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.chain }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: api-port
      name: api-port
      nodePort: {{ .Values.service.nodePort | default 30000 }}
  type: NodePort
