# Default values for hostname-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ovrclk/provider-services
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8188

ingress:
  enabled: false
  className: "akash-ingress-class"
  annotations: {}
  hosts: {}
