apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-validation-script
  namespace: {{ .Release.Namespace }}
data:
  inv_liveness_check.sh: |
    #!/bin/bash

    # Get the output and check if there are any nodes with null GPU info
    curl -sSf http://127.0.0.1:8080/v1/inventory | jq '.nodes[] | select(.resources.gpu.info == null)' | grep -q .
    result=$?

    # If grep found something (exit code 0), that's an error
    if [ $result -eq 0 ]; then
    echo "ERROR: Found nodes with GPU info set to null"
    exit 1
    else
    echo "No nodes with null GPU info found"
    exit 0
    fi
