apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-inventory
  namespace: akash-services
data:
  config.yaml: |
    version: v1
    cluster_storage:
      - default
      - beta2
    exclude:
      nodes: []
      node_storage: []


