apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-inventory
  namespace: akash-services
data:
  config.yaml: |
    version: v1
    cluster_storage:
      {{- range .Values.inventoryConfig.cluster_storage }}
      - {{ . }}
      {{- end }}
    exclude:
      nodes: {{ .Values.inventoryConfig.exclude.nodes | toYaml | nindent 6 }}
      node_storage: {{ .Values.inventoryConfig.exclude.node_storage | toYaml | nindent 6 }}


