apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-inventory
  namespace: akash-services
data:
  config.yaml: |
    version: v1
    cluster_storage:
{{- range .Values.inventoryConfig.cluster_storage }}
      - {{ . }}
{{- end }}
    exclude:
      nodes:
{{- range .Values.inventoryConfig.exclude.nodes }}
        - {{ . }}
{{- end }}
      node_storage: []
