apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-inventory
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: akash
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/component: operator
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: operator-inventory
        app.kubernetes.io/name: akash
        app.kubernetes.io/instance: inventory
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: operator-inventory
      containers:
        - name: operator-inventory
          image: ghcr.io/akash-network/provider
          args:
            - "provider-services"
            - "operator"
            - "inventory"
          imagePullPolicy: IfNotPresent
          env:
            - name: AP_CONFIG
              value: /akash/config.yaml
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
            - containerPort: 8081
              name: grpc
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /akash
      volumes:
        - name: config
          configMap:
            name: operator-inventory
