apiVersion: apps/v1
kind: Deployment
metadata:
  name: akash-inventory-operator
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: akash
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/component: operator
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: akash-inventory-operator
        app.kubernetes.io/name: akash
        app.kubernetes.io/instance: inventory
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: akash-inventory-operator
      containers:
        - name: akash-inventory-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["provider-services", "operator", "inventory"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
