appVersion: "2.46.0"
hostName: console-beta.akash.network

resources:
  limits:
    cpu: 1
    ephemeral-storage: 2Gi
    memory: 1Gi
  requests:
    cpu: 100m
    ephemeral-storage: 1Gi
    memory: 512Mi
