apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-dopplersecret
  namespace: doppler-operator-system
spec:
  config: {{ .Release.Namespace }}
  managedSecret:
    name: {{ .Chart.Name }}-secret
    namespace: {{ .Release.Namespace }}
    type: Opaque
  project: {{ .Chart.Name }}
  tokenSecret:
    name: console-token-secret
  verifyTLS: true
